client/package.json
copyfiles.js
core/connector.ts
core/package.json
examples/server.ts
fullstack/package.json
interfaces/package.json
jest.config.js
mitm-socket/package.json
mitm/package.json
package.json
plugin-utils/package.json
plugins/default-browser-emulator/package.json
plugins/default-human-emulator/package.json
plugins/execute-js/package.json
puppet-chrome/package.json
puppet/package.json
replay/package.json
testing/package.json

@ulxiee/commons had been updated to 1.5.5. This PR updated hero to use the latest commons.

feat: updated to use latest commons version

---

client/lib/Hero.ts

The Hero.on new events are now being typed correctly.

Fix Hero.on('new')

---

core/lib/CorePlugins.ts
core/lib/Session.ts
core/lib/SessionReplay.ts
interfaces/ICorePlugin.ts

This PR adds metadata to all callbacks in plugins so that a user can identify which session each callback is being made for.

feat(core): pass session summary to plugin fns

---

core/lib/CorePlugins.ts
core/lib/GlobalPool.ts
core/lib/SessionReplay.ts
core/test/GlobalPool.test.ts
interfaces/ICorePlugin.ts
interfaces/IPuppetBrowser.ts
interfaces/IPuppetContext.ts
puppet-chrome/lib/Browser.ts
puppet-chrome/lib/BrowserContext.ts
puppet-chrome/lib/FramesManager.ts
puppet-chrome/lib/Page.ts
puppet/index.ts

Also fixes an issue with indexDbName fetching

Add onBrowserLaunchConfiguration to add browser launch configs for a plugin

---

client/interfaces/IAwaitedEventTarget.ts
client/interfaces/IHeroCreateOptions.ts
client/interfaces/IJsPathEventTarget.ts
client/lib/AwaitedEventTarget.ts
client/lib/Hero.ts
client/lib/Tab.ts
client/lib/WebsocketResource.ts
package.json
plugins/default-browser-emulator/injected-scripts/navigator.ts
yarn.lock

Try number 2 at better typing for events with multiple parameters

chore: update typescript, event signatures

---

client/lib/CoreSession.ts
core/connections/ConnectionToClient.ts
core/lib/Session.ts
core/test/sessionResume.test.ts
mitm/lib/Http2SessionBinding.ts
plugins/default-browser-emulator/lib/helpers/setScreensize.ts

Adds a message to keepalive and a variable indicating if session is keptAlive on close. This feature now keeps open the command line if a script has sessionKeepAlive set.
A second Session.terminate command will actually close

feat(core): add keepalive message and cli

---

client/connections/ConnectionToCore.ts
client/interfaces/IPageStateDefinitions.ts
client/lib/CookieStorage.ts
client/lib/CoreCommandQueue.ts
client/lib/CoreEventHeap.ts
client/lib/CoreSession.ts
client/lib/CoreTab.ts
client/lib/Hero.ts
client/lib/PageState.ts
client/lib/Tab.ts
core/injected-scripts/pageEventsRecorder.ts
core/lib/FrameEnvironment.ts
core/lib/FrameNavigationsObserver.ts
core/lib/RemoteEventListener.ts
core/lib/RemoteEvents.ts
core/lib/Tab.ts
core/test/events.test.ts
core/test/pageState.test.ts
docs/main/BasicInterfaces/Hero.md
docs/main/BasicInterfaces/Tab.md
fullstack/test/waitForPageState.test.ts
interfaces/ICoreEventPayload.ts
interfaces/IPageStateResult.ts
plugin-utils/index.ts

Wait for one of many possible states to be loaded. This feature allows you to detect which page has been loaded based on a series of states, each containing one or more assertions that test for a particular page or template.
A common scraping challenge is to identify "which" page has loaded - which template? Is it a captcha? Is it the desired url? Am I redirecting through ad networks? 
Hero normally operates by running each command in order. This makes it a challenge to check for many possible states concurrently. `waitForPageState` runs the underlying commands for all state assertions in one round-trip to Chrome. This client-side can then synchronously evaluate a series of assertions to determine the currently loaded `Page State`.
Each Page State receives `assertion` functions (`assert` …

feat(client): waitForPageState(states, options)

---

core/lib/FrameNavigationsObserver.ts
fullstack/test/waitForLocation.test.ts
mitm/lib/MitmProxy.ts
mitm/lib/NetworkDb.ts

Small hole plugged: if you post to the same url, and waitForLocation('reload') it can't trigger a reload _or_ a change.

fix(core): can wait for reload on post

---

mitm-socket/lib/CertificateGenerator.ts
mitm/lib/MitmProxy.ts

fix(mitm): handle certs resolved before registered

---

client/connections/ConnectionToCore.ts
client/connections/ConnectionToRemoteCoreServer.ts
core/index.ts

Port fix from secret-agent. Client hangs on disconnect trying to send a Core.disconnect message after the connection closes, while waiting for a response.

fix(client): client hung on disconnect

---

client/lib/CoreSession.ts
core/lib/CorePlugins.ts
core/lib/GlobalPool.ts
interfaces/ICorePlugin.ts
plugins/default-browser-emulator/lib/helpers/configureBrowserLaunchArgs.ts
puppet-chrome/lib/Browser.ts
puppet-chrome/lib/BrowserContext.ts

- Added onNewPuppetContext to the plugin structure (needed by Chromealive)
- Fixed some bugs with incognito contexts
- Fixed a disconnect issue on client

feat(plugins): on browser context

---

client/lib/DomExtender.ts
core/injected-scripts/jsPath.ts
core/lib/FrameEnvironment.ts
core/lib/JsPath.ts
core/test/waitForElement.test.ts
docs/main/BasicInterfaces/FrameEnvironment.md
docs/main/BasicInterfaces/Tab.md
interfaces/INodeVisibility.ts
interfaces/IWaitForElementOptions.ts

Add an api to waitForElement for waiting for hidden elements.
NOTE: I had to update the API for excluding node visibility properties, otherwise it was just too hard to reason about what it meant to exclude properties.

feat(core): waitForHidden elements

---

core/injected-scripts/interactReplayer.ts
interfaces/IDomChangeEvent.ts
timetravel/injected-scripts/DomActions.ts
timetravel/injected-scripts/domReplayer.ts
timetravel/injected-scripts/domReplayerUI.ts
timetravel/lib/MirrorPage.ts
timetravel/lib/TimelineRecorder.ts
timetravel/player/TabPlaybackController.ts
timetravel/player/TimetravelPlayer.ts
timetravel/test/mirrorPage.test.ts

This PR introduces timetraveling backwards, but only to the live timeline for now. I wanted to give you a chance to see it so you can start to think about how we would change things if we can instantly move back on the timeline. I think it makes screenshots less needed... not sure if it means we can fully remove them or not.

feat(timetravel): allow backwards traveling

---

client/lib/FrameEnvironment.ts
client/lib/Hero.ts
client/lib/Tab.ts
core/injected-scripts/jsPath.ts
core/lib/JsPath.ts
core/lib/Tab.ts
core/test/interact.test.ts
docs/main/BasicInterfaces/FrameEnvironment.md
docs/main/BasicInterfaces/Hero.md
docs/main/BasicInterfaces/Tab.md
fullstack/test/document.test.ts
interfaces/IJsPathError.ts
interfaces/IMagicSelectorOptions.ts
interfaces/jsPathFnNames.ts

hero.magicSelector/All has been replaced with hero.querySelector/All that is now just a shortcut to window.document.querySelector/All.

The day the music died

---

client/connections/ConnectionToCore.ts
client/lib/CoreSession.ts
client/lib/DomExtender.ts
client/lib/Hero.ts

Added hero instance to its CoreSession to allow Databox integration.

feat: core session now has access to it's hero instance

---

core/injected-scripts/pageEventsRecorder.ts
core/lib/DevtoolsPreferences.ts
core/lib/JsPath.ts
core/lib/Tab.ts
core/lib/errorTypes.ts
core/models/FramesTable.ts
core/models/ResourcesTable.ts
interfaces/IDomChangeEvent.ts
plugins/default-human-emulator/index.ts
puppet-chrome/lib/DomStorageTracker.ts
timetravel/injected-scripts/domReplayer.ts
timetravel/lib/DomNode.ts
timetravel/lib/MirrorNetwork.ts
timetravel/lib/MirrorPage.ts
timetravel/player/TimetravelPlayer.ts

- Fix reloading jsPaths when paths change during an interact
- Resources not loading a second time in TimetravelPlayer or for redirects
- Publish events when paint ticks are navigated

Timetravel fixes

---

core/lib/DevtoolsPreferences.ts
mitm/handlers/HeadersHandler.ts
mitm/handlers/HttpRequestHandler.ts
mitm/handlers/HttpUpgradeHandler.ts
mitm/handlers/RequestSession.ts

I added a bypass to extension resources into the mitm. They will never resolve from the browser, so waiting here didn't make sense

fix(mitm): allow extension url access

---

docs/main/Advanced/ConnectionToCore.md
docs/main/Advanced/CookieStorage.md
docs/main/Advanced/FileChooser.md
docs/main/Advanced/Remote.md
docs/main/Advanced/Resource.md
docs/main/Advanced/Session.md
docs/main/Advanced/TimeTravel.md
docs/main/Advanced/UserProfile.md
docs/main/Advanced/WebsocketResource.md
docs/main/BasicInterfaces/AwaitedDOM.base.md
docs/main/BasicInterfaces/DetachedDOM.md
docs/main/BasicInterfaces/DomExtenders.md
docs/main/BasicInterfaces/FrameEnvironment.md
docs/main/BasicInterfaces/Hero.md
docs/main/BasicInterfaces/Interactions.md
docs/main/BasicInterfaces/Tab.md
docs/main/Help/troubleshooting.md
docs/main/Overview/BasicConcepts.md
docs/main/Overview/Configuration.md
docs/main/Overview/Introduction.md
docs/main/index.md

This PR does a pass-through on the docs to try to clean up changes since SecretAgent.
It also documents the updated Hero resource APIs

feat(docs): update documentation for unified docs

---

timetravel/player/TimetravelPlayer.ts

Small function to allow the offset percent to be retrieved for a commandId

feat(timetravel): find command offset

---

client/connections/ConnectionFactory.ts
client/connections/ConnectionToCore.ts
client/connections/ConnectionToRemoteCoreServer.ts
client/interfaces/IConnectionToCoreOptions.ts
client/package.json
client/test/basic.test.ts
core/connections/ConnectionToClient.ts
core/package.json
docs/main/BasicInterfaces/Hero.md
fullstack/package.json
interfaces/ISessionCreateOptions.ts
interfaces/package.json
mitm-socket/package.json
mitm/package.json
plugin-utils/package.json
plugins/default-browser-emulator/package.json
plugins/default-human-emulator/package.json
plugins/execute-js/package.json
puppet-chrome/package.json
puppet/package.json
testing/package.json
timetravel/package.json
yarn.lock

This PR converts Hero to look at ulixee config "servers.json" to see if a compatible Server version is available to automatically "route" to.

Automatic Server Port

---

docs/main/BasicInterfaces/AwaitedDOM-Extenders.md
docs/main/BasicInterfaces/Flow.md
docs/main/BasicInterfaces/Tab.md
docs/main/Help/migration-guide.md
docs/main/links.yaml
docs/scripts/generateAwaitedDOM.ts

I created a migration guide for SecretAgent users to move to Hero. We can probably put this in both repos if you like it.

feat: migration guide

---

core/env.ts
core/lib/InjectedScripts.ts
core/lib/Session.ts
package.json
yarn.lock

Options passed into Core's Session should parse strings into booleans.
There are a couple tests failing, but I confirmed that they are failing on main as well. They seem to be related to some commons code that you haven't pushed.

boolean options

---

core/lib/Session.ts
core/test/basic.test.ts
docs/main/AdvancedConcepts/Sessions.md
examples/server.ts

feat: add a session closed event

---

client/connections/ConnectionToHeroCore.ts
client/lib/Hero.ts
core/connections/ConnectionToHeroClient.ts
core/index.ts
core/lib/Session.ts
core/test/basic.test.ts
docs/main/AdvancedConcepts/Depoyment.md
docs/main/links.yaml

This PR adds some documentation for how to run a Hero Core/Server using the @ulixee/net library.
NOTE: in this PR, I've removed all of the auto-shutdown code from Hero/Core. Now that we are publishing playgrounds that auto-shutdown once an example is complete, I think the default behavior should not be to shutdown once there's no work left. You should have to close Hero. 
If you disagree, I can add this back, but that was my thinking.

Document Deployment Options (preparing to rename @ulixee/server)

---

client/interfaces/IHeroDefaults.ts
client/lib/Hero.ts
core/lib/Tab.ts
docs/main/BasicClient/Hero.md
docs/main/Overview/BasicConcepts.md
docs/main/Overview/Configuration.md
interfaces/IConfigureSessionOptions.ts
interfaces/ITabOptions.ts

Allow the ability to abort urls,
closing #164.

feat(blockedResourceUrls): expose and document

---

examples/plugins-ExtendHero.ts

where your custom function can build on the
rich features offered by the hero instance itself
this is for example useful to make advanced functions that allow you to solve captchas or other
complex repetitive work that you may wish to
use between your different hero scripts

feat(example): showcase how to extend hero with your own function

---

client/interfaces/IHeroDefaults.ts
client/lib/Hero.ts
core/index.ts
docs/main/BasicClient/Hero.md
interfaces/ICoreConfigureOptions.ts

Per @GlenDC, this PR enables disabling the auto-shutdown behavior in favor of allowing a user to manually close down Hero after work is complete.

feat(core): allow user to specify auto-shutdown

---

docs/advanced-concepts/deployment.md

Fullstack users should import it directly:
import { TransportBridge } from '@ulixee/net';

fix: fullstack instruction reflect changes to ulixee/shared/net/index.ts

---

.github/workflows/js-branch.yml
core/dbs/SessionDb.ts
core/lib/CommandRecorder.ts
core/lib/Session.ts
core/lib/Tab.ts
core/test/user-profile.test.ts
timetravel/lib/DomStateGenerator.ts
timetravel/lib/MirrorPage.ts

This PR:
- unlinks (nulls out) inter references between hero Tab/Session/CommandRecorder
- Removes "WAL" mode default for SQLite. It causes weird behavior if a database is not closed
- Builds a javascript release for every branch so that branches/latest head can be used in npm

Fix Memory Leak

---

client/package.json
core/package.json
docs/basic-client/hero.md
docs/plugins/core-plugins.md
end-to-end/package.json
interfaces/IConfigureSessionOptions.ts
interfaces/package.json
package.json
yarn.lock

fix(core): remove awaited-dom no-default-lib directive

feat(core): proxy local dns feature

---

client/interfaces/IHeroDefaults.ts
client/lib/Hero.ts
core/lib/Tab.ts
docs/basic-client/hero.md
docs/overview/configuration.md
end-to-end/test/resources.test.ts
interfaces/IConfigureSessionOptions.ts
interfaces/ITabOptions.ts
yarn.lock

Added ability to intercept certain requests by matching url (string | RegExp).
Body, statusCode and headers can be manipulated.
Feature for #236

Ability to set network responses

---

docs/advanced-concepts/deployment.md

Should help to get started with production deployment of `hero`.

Add chapter "Secure deployment via Nginx, SSL and Basic Auth"

---

client/package.json
core/package.json

Add types declaration in package.json exports
