ulixee/hero

core/connections/ConnectionToClient.ts, core/index.ts, core/injected-scripts/interactReplayer.ts, core/lib/GlobalPool.ts, core/lib/Session.ts, core/lib/Tab.ts, core/test/resources.test.ts, core/test/sessionResume.test.ts, interfaces/IPuppetPage.ts, mitm/test/MitmRequestAgent.test.ts, plugins/default-browser-emulator/injected-scripts/tsconfig.json, puppet-chrome/lib/Page.ts, tsconfig.json
Add events to Core:
- GlobalPool: 'session-created', 'browser-launched'
- Session: 'tab-created'
Add more reliable shutdown for keep-alive sessions
Ts: enable strict bind apply to typecheck bind calls
=> feat(core): add puppet and session events

puppet/lib/launchProcess.ts
Makes sure chrome is always killed when the process is about to exit (instead of doing a graceful shutdown)
=> feat(puppet): always kill chrome on shutdown

client/lib/CoreSession.ts, client/lib/CoreSessions.ts, plugins/default-browser-emulator/test/media.test.ts
If the server disconnected (ie, you kill ChromeAlive), the cli would stay up
=> Close the cli prompt when connection disconnects

client/lib/CoreSession.ts, core/injected-scripts/interactReplayer.ts, core/injected-scripts/jsPath.ts, core/lib/CommandRunner.ts, core/lib/GlobalPool.ts, core/lib/Interactor.ts, core/lib/Session.ts, core/test/connection.test.ts, fullstack/test/emulate.test.ts, interfaces/IDevtoolsSession.ts, interfaces/IPuppetBrowser.ts, interfaces/IPuppetContext.ts, jest.config.js, plugins/default-browser-emulator/index.ts, plugins/default-browser-emulator/lib/helpers/setScreensize.ts, plugins/default-browser-emulator/package.json, puppet-chrome/lib/Browser.ts, puppet-chrome/lib/BrowserContext.ts, puppet-chrome/lib/Frame.ts, puppet/index.ts, puppet/lib/launchProcess.ts, puppet/test/BrowserContext.test.ts, puppet/test/Page.test.ts, yarn.lock
This PR adds an ability to use the default (non incognito) context in hero. This is primarily needed to run ChromeAlive's extension with an ability to group tabs.
Other fixes include:
- Upgrade default browser to chrome 89 - this is needed to enable styling tabGroups in extensions
- Fix closing issues from client when hero instance closed from server
- Fix node highlighting in page
- Fix interact issue where navigating to a known "id" could incorrectly think it was a coordinate
=> Default context

core/lib/Session.ts, docs/main/BasicInterfaces/Hero.md, interfaces/ICorePlugin.ts, interfaces/ISessionCreateOptions.ts, mitm/handlers/HttpRequestHandler.ts, mitm/handlers/RequestSession.ts, plugins/default-browser-emulator/index.ts
This PR was made because requests that fail internally are showing stack traces in the headed UI, which is not desirable.
This PR also adds dns over tls configuration from client
=> Mitm - disable including stack traces in network requests when headed, allow client specifying dns over tls provider

core/injected-scripts/interactReplayer.ts, core/models/ScreenshotsTable.ts, core/models/StorageChangesTable.ts, interfaces/ITimelineMetadata.ts, timetravel/lib/MirrorNetwork.ts, timetravel/lib/MirrorPage.ts, timetravel/lib/PageStateGenerator.ts, timetravel/lib/TimelineBuilder.ts, timetravel/player/TimetravelPlayer.ts
Feature:
- Track storage changes at each tick for a timeline
Fixes: 
- Tracking mouse incorrectly for a person moving the mouse
- A second tab opened would break timetravel inside page state (was a conflict of "documents" in MirrorNetwork)
=> fix(timetravel): multi-tabs conflicting documents

client/lib/CoreCommandQueue.ts, client/lib/CoreEventHeap.ts, client/lib/Hero.ts, client/lib/PageState.ts, client/lib/ScriptInstance.ts, client/lib/Tab.ts, client/package.json, client/test/basic.test.ts, core/package.json, fullstack/package.json, interfaces/package.json, mitm-socket/package.json, mitm/package.json, plugin-utils/package.json, plugins/default-browser-emulator/package.json, plugins/default-human-emulator/package.json, plugins/execute-js/package.json, puppet-chrome/package.json, puppet/package.json, testing/package.json, timetravel/package.json, yarn.lock
Use a common standard for the stacktraces we use during development.
This PR moves Hero off of using source-map-support in favor of directly using the source-map library from Mozilla. Unfortunately, they've moved to an async model that makes it difficult to support stack traces (which are synchronous). I used a fork of that library that is porting some of their performance improvements (minus wasm) (source-map-js). In a recent ticket, the mozilla lib is considering taking a PR, so we can possibly move back to that once it's up (https://github.com/mozilla/source-map/issues/370#issuecomment-823403894)
=> feat(client): add serialized callstack

client/lib/CoreFrameEnvironment.ts, client/lib/DomExtender.ts, client/lib/FrameEnvironment.ts, client/lib/Hero.ts, client/lib/SetupAwaitedHandler.ts, client/lib/Tab.ts, core/injected-scripts/jsPath.ts, core/lib/FrameEnvironment.ts, core/lib/Tab.ts, docs/main/BasicInterfaces/FrameEnvironment.md, docs/main/BasicInterfaces/Hero.md, docs/main/BasicInterfaces/Tab.md, fullstack/test/document.test.ts, interfaces/IJsPathError.ts, interfaces/IMagicSelectorOptions.ts, interfaces/jsPathFnNames.ts
NOTE: we should merge Pull Request 54 and 55 first.
This PR adds 2 functions to frameEnvironment/tab/hero:
magicSelector and magicSelectorAll
These functions on their own simply allow a user to provide a list of selectors and verify that a querySelector (or querySelectorAll) returns the same elements from the provided list of querySelectors.
When a magicSelector is encountered, an event is broadcast at a tab level (magic-selector/magic-selector-all) with the options provided. Those options can be manipulated if need by (eg, by Superhero) to provide a larger list of querySelectors to test, or to trigger UI changes in Superhero.
=> feat(core): magic selectors

core/lib/FrameNavigations.ts, core/lib/Tab.ts, fullstack/test/waitForLocation.test.ts
Bug reported by user: after a form submission that redirects in-page "before the resource is loaded" will never resolve the resource, so the location change hangs.
=> fix(core): in page nav not resolving resource

client/lib/DomExtender.ts, core/injected-scripts/jsPath.ts, core/lib/FrameEnvironment.ts, core/lib/JsPath.ts, core/test/waitForElement.test.ts, docs/main/BasicInterfaces/FrameEnvironment.md, docs/main/BasicInterfaces/Tab.md, interfaces/INodeVisibility.ts, interfaces/IWaitForElementOptions.ts, plugins/default-human-emulator/index.ts
Allows customizing the waitForVisible and waitForElement functions to specific individual properties of getComputedVisibility. By default, we now ignore isOnscreen* and isUnobstructed properties when determining if an element is "visible"
=> Wait for visible

client/lib/CoreCommandQueue.ts, core/connections/ConnectionToClient.ts, fullstack/test/detach.test.ts
When there are lots of detached commands or output to record, we could lose changes during close.
=> fix(client): wait for command flush

client/index.mjs, client/index.ts, client/lib/DomExtender.ts
- Renamed $getComputedVisibility() to a $computedVisibility getter.
- Added $clearValue() to clear an input text field
- Added $map for NodeList and HTMLCollection. There are many times during extraction where you want to use querySelectorAll to grab multiple elements and then extract from all of them. Being forced to use a for loop every time is frustrating.
=> feat: added some more dom extenders

client/lib/DomExtender.ts, client/lib/Resource.ts, client/lib/ResourceResponse.ts, client/lib/WebsocketResource.ts, core/lib/Tab.ts, fullstack/test/basic.test.ts
- resource.data is renamed to resource.buffer
- resource.text was converted from method to getter.
- resource.json was converted from method to getter.
- snuck in a new dom extender ;)
=> feat: renamed resource outputs to getters: buffer, text, json

client/lib/DomExtender.ts, client/lib/FrameEnvironment.ts, client/lib/FrozenFrameEnvironment.ts, core/injected-scripts/MouseEvents.ts, core/injected-scripts/jsPath.ts, core/lib/Interactor.ts, core/lib/JsPath.ts, core/lib/MouseListener.ts, core/models/ResourcesTable.ts, core/test/interact.test.ts, core/test/user-profile.test.ts, core/test/waitForElement.test.ts, docs/main/BasicInterfaces/FrameEnvironment.md, docs/main/BasicInterfaces/Tab.md, fullstack/test/document.test.ts, fullstack/test/tab.test.ts, interfaces/IInteractions.ts, interfaces/IInteractionsHelper.ts, interfaces/IMouseResult.ts, interfaces/INodeVisibility.ts, interfaces/IWaitForElementOptions.ts, plugins/default-human-emulator/index.ts, plugins/default-human-emulator/test/emulator.test.ts
1. Interactions now confirm that the proper element is being clicked on mousedown and cancel the mouse event if it's not right. This allows us to try to move out of the way of animating elements
2. DomExtenders: $isClickable, $isVisible (removes $nodeVisibility)
3. In nodeVisibility, isVisible is now the result of all "visibility" properties, and isClickable is the clickable ones
=> fix(interaction): cancel mouse clicks on mousedown

client/lib/CoreSession.ts, client/lib/Hero.ts, core/dbs/SessionDb.ts, core/injected-scripts/pageEventsRecorder.ts, core/lib/Commands.ts, core/lib/DetachedTabState.ts, core/lib/FrameNavigations.ts, core/lib/FrameNavigationsObserver.ts, core/lib/Session.ts, core/lib/Tab.ts, core/models/DevtoolsMessagesTable.ts, core/models/DomChangesTable.ts, core/test/navigation.test.ts, fullstack/test/tab.test.ts, fullstack/test/websocket.test.ts, package.json, puppet-chrome/lib/BrowserContext.ts, timetravel/injected-scripts/domReplayerUI.ts, timetravel/lib/MirrorPage.ts, timetravel/player/TimetravelPlayer.ts, yarn.lock
1) Fix a bug that we were tracking removals of doNotTrack elements in timetravel
2) If you used "goBack" on a single page app, it could hang
3) Add an overlay to frozen tabs so you can see that they are frozen
4) Fix git:// paths in package.json to https. git: was deprecated
Experimental feature:
Ability to load frozen tabs from a session database - this enables you to separate the logic to extract data from a session from the interaction to create it.
=> Experimental: Load Frozen Tabs from Db; Bug fixes

client/lib/CoreFrameEnvironment.ts, client/lib/CoreSession.ts, client/lib/DomExtender.ts, client/lib/Fragment.ts, client/lib/FrozenFrameEnvironment.ts, client/lib/Hero.ts, core/dbs/SessionDb.ts, core/lib/DetachedTabState.ts, core/lib/FrameEnvironment.ts, core/lib/JsPath.ts, core/lib/Session.ts, core/lib/Tab.ts, core/models/DomChangesTable.ts, core/models/FragmentsTable.ts, core/models/FrameNavigationsTable.ts, fullstack/test/fragments.test.ts
This PR adds an ability to save "fragments" in the dom that are static snapshots which can later be retrieved.
Dom nodes are saved with a name using $extractLater. They can be retrieved by importing all dom fragments and then calling getFragment(name).
Heroboxes will automatically retrieve all dom fragments
=> feat(core): collect and recreate fragments

core/injected-scripts/interactReplayer.ts, core/injected-scripts/pageEventsRecorder.ts, core/lib/FrameEnvironment.ts, core/lib/InjectedScripts.ts, core/lib/Session.ts, core/models/FrameNavigationsTable.ts, interfaces/IDomChangeEvent.ts, interfaces/IPuppetContext.ts, interfaces/IPuppetPage.ts, package.json, puppet-chrome/lib/BrowserContext.ts, puppet-chrome/lib/DomStorageTracker.ts, puppet-chrome/lib/FramesManager.ts, puppet-chrome/lib/Page.ts, timetravel/injected-scripts/DomActions.ts, timetravel/lib/CommandTimeline.ts, timetravel/lib/MirrorPage.ts, timetravel/lib/TimelineRecorder.ts, timetravel/player/TimetravelPlayer.ts, timetravel/test/mirrorPage.test.ts
Very small changes to fix misalignment between the "timeline" bar.
Along the way, fixed a few issues:
- disable storage tracking in mirror pages (can throw off cookies)
- mouse not tracking on timetravel
- backwards "location" changes weren't working
- fix restoring the navigations from db when creating a timeline for the mirrorpage (this was the main issue)
-
=> Timeline <-> dom misaligned

client/lib/CoreFrameEnvironment.ts, client/lib/CoreTab.ts, client/lib/DomState.ts, client/lib/DomStateHandler.ts, client/lib/Hero.ts, client/lib/Tab.ts, core/lib/DomStateListener.ts, docs/main/BasicInterfaces/Hero.md, docs/main/BasicInterfaces/Tab.md, fullstack/test/domState.test.ts, fullstack/test/flowHandlers.test.ts, interfaces/IDomState.ts
All of these except the last are ones we discussed yesterday. I implemented them in Hero to see if it made my scripts feel simpler and they did, so I submitted a PR.
1) The `allTrue` in State has been simplified down to just `all` with the first argument being `assert` and not `{ assert }`:
```
hero.waitForState({
all(assert) {
....
}
});
```
2) The State Methods (checkState, waitForState, and registerFlowHandler) now accept a simplified first argument of just the `all(assert)` callback:
```
hero.waitForState(assert => {
....
});
```
3) `checkFlowHandlers` has been renamed to `triggerFlowHandlers` to be more precise in what it does.
4) `checkState` has been renamed to `validateState`. I understand why we went with "checkState" as "ensureState" wasn't quite accurate (it doesn't actually …
=> Syntax changes and renames to State and Flow Handlers

client/lib/CoreFrameEnvironment.ts, client/lib/DomExtender.ts, client/lib/FrameEnvironment.ts, client/lib/Hero.ts, client/lib/Tab.ts, core/injected-scripts/jsPath.ts, fullstack/test/domExtenders.test.ts, interfaces/jsPathFnNames.ts, puppet/index.ts
This PR adds 3 dom extenders:
- $hasFocus - is a field focused
- $xpathSelector(path, ordered = false) - runs a singleNode xpath selector
- $xpathSelectorAll(path, ordered = false) - runs multiNode xpath selector
Also fixes an issue where interact wasn't working on xpath elements due to not evaluating the parameters to the xpath
=> feat(client): focus and xpath dom extenders

client/lib/CoreSession.ts, client/lib/DomExtender.ts, client/lib/Hero.ts
This will allow Databox's DomExtensions to register multiple extract functions in Hero CoreSession, both for ChromeAlive to know when extractors are finished (this will require connecting it into core). It also allows DataboxInternal to track the same extract promises that DomExtensions added.
=> feat: added extractorPromises into Client's CoreSession

client/interfaces/IFlowHandler.ts, client/lib/CoreCommandQueue.ts, client/lib/CoreTab.ts, client/lib/DomState.ts, client/lib/DomStateHandler.ts, client/lib/Hero.ts, client/lib/Tab.ts, fullstack/test/domState.test.ts, fullstack/test/flowHandlers.test.ts, interfaces/IDomState.ts
This PR forces names to be provided for flow handlers and removes them from DomState/waitForState.
=> feat(client): for flow handler names

client/interfaces/IWaitForResourceFilter.ts, client/interfaces/IWaitForResourcesFilter.ts, client/lib/CoreTab.ts, client/lib/Hero.ts, client/lib/Resource.ts, client/lib/Tab.ts, client/test/waitForResource.test.ts, core/lib/Resources.ts, core/lib/Tab.ts, core/test/resources.test.ts, fullstack/test/resources.test.ts, fullstack/test/tab.test.ts, fullstack/test/websocket.test.ts
It became apparent when writing out example docs in Databox that we need both singular and plural resource apis. Otherwise you CAN'T do a findResource and actually find all of them. And once you have both `findResource` and `findResources`, it just doesn't make sense to have a method called `waitForResource` that returns multiple.
This PR changes our resource APIs to the following:
1. waitForResource is renamed to waitForResources
2. waitForResource is now a singular resource lookup. There is no "done" function required if you use a filter function. The function escapes when you return.
3. findResource returns a single resource since the page loaded (http request, not in-page load)
4. findResources finds many resources since the page loaded (http request, not in-page load)
=> feat(client): add single resource search apis

client/lib/Hero.ts, client/lib/Tab.ts, docs/main/BasicInterfaces/Tab.md, fullstack/test/flow.test.ts, interfaces/IFlowCommandOptions.ts
FlowCommands now take only 2 parameters. You can either provide 2 parameters where the exitState is a callback:
```js
await hero.flowCommand(async () => {
const field = await hero.querySelector('#text').$waitForVisible();
await field.$type('test');
}, (assert) => {
assert(hero.querySelector('#text').value, 'test');
});
```
or 2 parameters where the second parameter is an object with options:
```js
await hero.flowCommand(async () => {
const field = await hero.querySelector('#text').$waitForVisible();
await field.$type('test');
}, {
maxRetries: 2,
exitState(assert) {
assert(hero.querySelector('#text').value, 'test');
},
});
```
=> Adjust FlowCommand syntax

core/lib/Session.ts, interfaces/IPuppetContext.ts, interfaces/IPuppetPage.ts, puppet-chrome/lib/Page.ts, timetravel/player/TimetravelPlayer.ts
Some changes needed for the `tabs` ulixee PR:
- PuppetPage instances now have an optional groupName property. This is used in ChromeAlive's SessionObserver to filter only the Live pages/tabs.
- Removed some unneeded events from TimetravelPlayer. SessionObserver's integration with extension tabs has changed substantially.
=> Tabs support

core/lib/CorePlugins.ts, interfaces/ICorePlugin.ts, interfaces/package.json, mitm/package.json, puppet-chrome/lib/Browser.ts, puppet-chrome/lib/BrowserContext.ts, puppet-chrome/lib/Page.ts, puppet-chrome/package.json, yarn.lock
- Plugins can now use onDevtoolsPanelDetached in order to cleanup from onDevtoolsPanelAttached.
- Upgrafded devtools-protocol module
=> On devtools detached

core/lib/InjectedScripts.ts, timetravel/injected-scripts/domReplayer.ts, timetravel/lib/MirrorNetwork.ts, timetravel/lib/MirrorPage.ts
When you access ContentWindow or Parent from an isolated Chrome context, it seems to create additional isolated contexts. This creates a situation where in TimeTravel, we're ending up with many HeroWorlds, and then we don't know which one has pre-installed the domReplayer script and other things. This issue does not seem to exist when things are run in the default context, however, if you "disable" javascript, it also disables javascript in the main context. I was able to workaround this by re-enabling javascript in the default context, but adding a ContentSecurityPolicy that says only scripts with the nonce "hero-timetravel" should be allowed - ie, no scripts. The main downside is this creates logging about blocked content security policies. However... it fixes the breaking history. I'm …
=> fix(timetravel): timetravel creating dup contexts

core/injected-scripts/domStorage.ts, core/injected-scripts/indexedDbRestore.ts, core/lib/InjectedScripts.ts, core/lib/Resources.ts, core/lib/Session.ts, core/lib/UserProfile.ts, core/test/user-profile.test.ts, fullstack/test/filechooser.test.ts, mitm/handlers/HeadersHandler.ts, mitm/handlers/HttpRequestHandler.ts, mitm/interfaces/IBrowserRequestMatcher.ts, mitm/test/basic.test.ts, puppet-chrome/lib/Frame.ts
This PR changes user profiles so they restore in iframe on the first about:blank tab. As a reminder, to restore storage in Chrome, you need to have frames open to each security context. Then we set local/session storage into those tabs. This is a significant speed improvement for bigger profiles, and fixes issues with filechoosers not working when multiple domains are restored, and issues with ChromeAlive losing focus when opening many tabs to restore storage.
----
Session storage is destroyed after a tab is closed, so without updating chrome storage, this is the only way I know to add storage. I've explored whether we could intercept requests to frames/pages and restore dom storage on the fly. However, I can't figure out how to make this the first thing that loads while also silently …
=> fix(core): restore user profiles in frames

core/lib/CorePlugins.ts, core/lib/FrameEnvironment.ts, core/lib/GlobalPool.ts, core/lib/Session.ts, docs/main/BasicInterfaces/Hero.md, docs/main/Plugins/BrowserEmulators.md, examples/news.ycombinator.com.ts, examples/sessionResume.ts, examples/show-browser.js, interfaces/ICorePlugin.ts, interfaces/ILaunchOptions.ts, interfaces/IPuppetLaunchArgs.ts, interfaces/ISessionCreateOptions.ts, plugin-utils/lib/BrowserEngine.ts, plugins/default-browser-emulator/index.ts, plugins/default-browser-emulator/lib/helpers/configureBrowserLaunchArgs.ts, puppet-chrome/index.ts, puppet/index.ts, timetravel/lib/MirrorContext.ts, timetravel/lib/MirrorPage.ts, timetravel/lib/TimelineWatch.ts, timetravel/test/mirrorPage.test.ts
Modified the TimelineRecorder (which used to activate and cancel creating timestamps) to a TimelineWatch, which will emit events when the timeline changes, and will optionally extend the timeline (ie, close time) by X ms after the last command, or X ms after the last status. This allows us to say, extend the session 2 seconds after the last command finished, or 2 seconds after ContentLoaded occurs, which is important for making the StateGenerator usable.
Also changed session create options `showBrowser` to `showChrome` and `showBrowserInteractions` to `showChromeInteractions`
=> feat(timetravel): timeline extender ms after cmd

docs/main/AdvancedClient/FrameEnvironment.md, docs/main/AdvancedClient/Tab.md, docs/main/BasicClient/AwaitedDOM-Extensions.md, docs/main/BasicClient/Hero.md, docs/main/BasicClient/Interactions.md
Some paths in the documentation are wrong and result in broken urls.
This PR fixes these paths and has been confirmed to work when building locally.
Example found on https://ulixee.org/docs/hero/basic-client/tab:
- [SuperDocument](https://ulixee.org/docs/awaited-dom/super-document)
Should be:
- [SuperDocument](https://ulixee.org/docs/hero/awaited-dom/super-document)
=> Update wrong documentation urls

core/connections/ConnectionToHeroClient.ts, core/index.ts, end-to-end/test/basic.test.ts, end-to-end/test/resources.test.ts, timetravel/test/DomStateGenerator.test.ts
A legacy of our old model of automatically shutting down idle connections was still present in ConnectionToHeroClients. I've changed this so that you have to explicitly register that you'd like to disconnect "idle" connections via a Core property. As this behavior is only desirable in a "hosting" situation, I've left it undocumented for now.
=> fix: disable auto-shutdown of idle connections

core/dbs/SessionDb.ts, core/lib/Session.ts, core/test/basic.test.ts, core/test/sessionResume.test.ts, docs/basic-client/hero.md, interfaces/ISessionCreateOptions.ts
Add a configuration variable to delete session databases after use per Hero instance. This has been requested frequently. By default, this is not enabled - in particular since we are adding many features to have a full-fledged Hero instance that can run off a prior session, which we believe will change the default way many people use Hero (eg, into a two-phased collect and then extract process).
=> feat(session): config to delete sessions

client/interfaces/ICoreSession.ts, client/lib/Hero.ts, client/lib/HeroReplay.ts, core/dbs/SessionsDb.ts
Add an on connected event for both Hero and HeroReplay that will trigger when the session is connected. Had to create this because the act of "accessing" the coreSessionPromise was creating the session before, which meant you couldn't then use plugins.
=> feat(hero): add connected/session created event

client/lib/CoreTab.ts, client/lib/FlowCommand.ts, client/lib/Hero.ts, client/lib/Tab.ts, docs/advanced-client/tab.md, end-to-end/test/flow.test.ts
Expose 'triggeredFlowHandler', and 'matchedFlowHandlers' to caller so he knows what hero did when called manually. 
This function can also now be called multiple times as long as hero is making progress (matchedFlowHandlers is shrinking).
=> feat: expose triggerFlowHandler internal data

core/index.mjs
Fix missing named exports for `hero-core`. Replacing copied exports copied from unlocked.Browser/Human with actual core exports.
=> fix: sync core ES exports with TS exports

docs/advanced-client/frame-environment.md
In docs the `FrameEnvironment.frameId` is described as `string` but in the class definition it is `number`.
This PR change the data type in doc to `number`, so it conforms to the reality.
=> Fix frameId data type in frame-environment.md

core/lib/CorePlugins.ts, core/lib/Session.ts, core/test/connection.test.ts, core/test/domRecorder.test.ts, docs/basic-client/hero.md, interfaces/ICorePlugin.ts, interfaces/ICorePluginCreateOptions.ts, interfaces/ISessionCreateOptions.ts, package.json, plugins/execute-js/package.json, plugins/execute-js/test/config.test.ts, testing/TestHero.ts, yarn.lock
Support configuring core plugins and unblocked plugins. This is done through an object which uses plugin.id as key to index. Each plugin can have a custom config in there of type object. Config can also be true or false: true will always activate the plugin and skip shouldActivateCheck, false will always disable the plugin and skip shouldActivateCheck. Implementation in hero core is almost exact same as in https://github.com/ulixee/unblocked/pull/101 except some minor type differences. The options are passed in through hero constructor. Constructor now also has support to configure Unblocked plugin classes per hero session.
=> Feat  configure plugins

agent/docs/Page.md, agent/main/lib/BrowserContext.ts, agent/main/lib/FramesManager.ts, agent/main/lib/InjectedScripts.ts, agent/main/lib/Page.ts, agent/main/lib/WebsocketMessages.ts, agent/main/lib/WebsocketSession.ts, commons/lib/utils.ts, commons/test/utils.test.ts, core/lib/InjectedScripts.ts, core/models/DevtoolsMessagesTable.ts, plugins/default-browser-emulator/interfaces/INewDocumentInjectedScript.ts, plugins/default-browser-emulator/lib/plugins/FirstPartyCookiesPlugin.ts, plugins/default-browser-emulator/lib/setPageDomOverrides.ts, specification/agent/browser/IPage.ts, timetravel/lib/MirrorNetwork.ts
This PR merges the concepts of adding new document scripts with adding callbacks to the page. A few other small changes of note:
1. Added no-cors to the websocket callback
2. Only add the websocket when a callback is present (they're scoped to the fn, so it shouldn't have any impact)
3. Add some csp headers to time travel (needed for electron)
=> Callbacks for NewDocumentScripts

agent/main/lib/Resources.ts
I ran into an issue with a website that had the header: ```{ 'Set-Cookie': '' }```. This was causing the following fatal error every time I tried to call _hero.goto()_:
```
ERROR [hero-core/index] UnhandledRejection { context: {}, sessionId: null, sessionName: undefined } ReferenceError: Cookie is not defined
at Resources.recordCookies
```
This simple fix resolves the issue and _hero.goto()_ now behaves as expected.
=> Solve ReferenceError: Cookie is not defined

.github/workflows/lint-and-test.yml, README.md
Github made ubuntu 24 the default for latest-ubuntu. This break ci testing, until that is fixed use ubuntu 22.
=> Use ubuntu 22 in tests until issue with 24 is fixed

agent/main/lib/Console.ts, agent/main/lib/NetworkManager.ts
When using fetch with http scheme inside chrome internal url such as `chrome://version` it breaks the entire window, using a scheme such as data:// or file:// gives an error in console but still allows everything to work
=> fix(agent): support callbacks in chrome internal urls

agent/main/lib/Agent.ts
After upgrading to the [v2.0.0-alpha.32](https://github.com/ulixee/hero/releases/tag/v2.0.0-alpha.32) release, I started seeing `net::ERR_PROXY_CONNECTION_FAILED` errors when using a socks5 URL in `upstreamProxyUrl` with mitm disabled. The cause seems to be [99467940](https://github.com/ulixee/hero/commit/99467940232f004d6cc1a22a3755489083c627be) which parses `upstreamProxyUrl` into a `URL` object and then uses the `origin` property as the proxy address. Unfortunately, for URLs with the `socks5` protocol, the origin property is always `null`. This is a simple workaround that constructs the address from the `protocol` and `host` properties instead.
=> fix(agent): fix proxyConnectionInfo for socks5 URLs
